# Book settings
title: Imaging statistics
#logo: 'logo.png'
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url: https://github.com/guiwitz/ImagingStats

html:
  use_repository_button: true

sphinx:
  config:
    html_extra_path: ['rise_presentation']